version: '3'

services:
  nginx-proxy:
    # image: jwilder/nginx-proxy:${NGINX_PROXY_TAG:-latest}
    build:
      context: ./nginx/build
      args:
        nginx_proxy_tag: ${NGINX_PROXY_TAG:-latest}
    container_name: nginx-proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
      - "127.0.0.1:8082:8082"
    volumes:
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_vhost.d:/etc/nginx/vhost.d
      - nginx_dhparam:/etc/nginx/dhparam
      - nginx_html:/usr/share/nginx/html
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-net
    extra_hosts:
      - "dockerhost:172.16.254.1"

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:${LE_COMPANION_TAG:-latest}
    container_name: letsencrypt-companion
    restart: unless-stopped
    env_file:
      - le-companion.env
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost.d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-net
    extra_hosts:
      - "dockerhost:172.16.254.1"
    depends_on:
      - nginx-proxy

networks:
  proxy-net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.254.0/24

volumes:
  nginx_certs:
  nginx_dhparam:
  nginx_vhost.d:
  nginx_html:
